#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""39 İlçe SEO Veri Seti — Mikro-yerel içerik, komşu ilçeler, semtler"""

DISTRICTS = [
    {
        "name": "Adalar",
        "slug": "adalar-evden-eve-nakliyat",
        "old_file": "ilceler/adalar-nakliyat.html",
        "population": "16.000",
        "side": "Anadolu",
        "semtler": ["Büyükada", "Heybeliada", "Burgazada", "Kınalıada"],
        "neighbors": ["Kadıköy", "Maltepe", "Kartal"],
        "neighbor_slugs": ["kadikoy-evden-eve-nakliyat", "maltepe-evden-eve-nakliyat", "kartal-evden-eve-nakliyat"],
        "micro_content": "Ada'dan ada'ya, karadan karaya... Adalar'ın eşsiz deniz ulaşımı koşullarına uygun özel feribot koordinasyonu ile eşyalarınızı güvenle taşıyoruz. Büyükada'nın fayton sokaklarından Heybeliada'nın dar patikalarına kadar ada nakliyatında uzman ekibimizle yanınızdayız.",
        "geo_detail": "Marmara Denizi'ndeki dört adada özel lojistik planlama ile vapur ve feribot koordinasyonlu taşıma.",
        "price_note": "feribot koordinasyonu ve ada lojistiği dahil"
    },
    {
        "name": "Arnavutköy",
        "slug": "arnavutkoy-evden-eve-nakliyat",
        "old_file": "ilceler/arnavutkoy-nakliyat.html",
        "population": "330.000",
        "side": "Avrupa",
        "semtler": ["Hadımköy", "Haraççı", "Bolluca", "İmrahor", "Tayakadın"],
        "neighbors": ["Başakşehir", "Eyüpsultan", "Çatalca", "Esenyurt"],
        "neighbor_slugs": ["basaksehir-evden-eve-nakliyat", "eyupsultan-evden-eve-nakliyat", "catalca-evden-eve-nakliyat", "esenyurt-evden-eve-nakliyat"],
        "micro_content": "İstanbul Havalimanı'nın komşusu Arnavutköy, hızla büyüyen yeni yerleşim bölgeleriyle dikkat çekiyor. Hadımköy sanayi bölgesinden Bolluca'nın yeni konut projelerine kadar geniş bir alanda profesyonel nakliyat hizmeti sunuyoruz.",
        "geo_detail": "İstanbul Havalimanı yakınındaki gelişen bölgede, yeni site ve konut projelerine uzman taşıma hizmeti.",
        "price_note": "yeni yerleşim bölgelerine özel planlama dahil"
    },
    {
        "name": "Ataşehir",
        "slug": "atasehir-evden-eve-nakliyat",
        "old_file": "ilceler/atasehir-nakliyat.html",
        "population": "430.000",
        "side": "Anadolu",
        "semtler": ["Ataşehir Bulvarı", "İçerenköy", "Kayışdağı", "Barbaros", "Ferhatpaşa"],
        "neighbors": ["Kadıköy", "Ümraniye", "Sancaktepe", "Maltepe"],
        "neighbor_slugs": ["kadikoy-evden-eve-nakliyat", "umraniye-evden-eve-nakliyat", "sancaktepe-evden-eve-nakliyat", "maltepe-evden-eve-nakliyat"],
        "micro_content": "İstanbul Finans Merkezi'nin kalbindeki Ataşehir, modern rezidansları ve iş merkezleriyle Anadolu yakasının en dinamik ilçesidir. İçerenköy'ün yerleşik mahallelerinden Ataşehir Bulvarı'nın gökdelenlerine kadar her tür taşımada uzmanız.",
        "geo_detail": "Finans merkezi ve modern rezidanslar bölgesinde, asansörlü ve özel ekipmanla yüksek katlı bina taşımacılığı.",
        "price_note": "yüksek katlı bina ve rezidans taşıma dahil"
    },
    {
        "name": "Avcılar",
        "slug": "avcilar-evden-eve-nakliyat",
        "old_file": "ilceler/avcilar-nakliyat.html",
        "population": "450.000",
        "side": "Avrupa",
        "semtler": ["Ambarlı", "Cihangir", "Denizköşkler", "Firuzköy", "Gümüşpala"],
        "neighbors": ["Küçükçekmece", "Esenyurt", "Beylikdüzü", "Büyükçekmece"],
        "neighbor_slugs": ["kucukcekmece-evden-eve-nakliyat", "esenyurt-evden-eve-nakliyat", "beylikduzu-evden-eve-nakliyat", "buyukcekmece-evden-eve-nakliyat"],
        "micro_content": "Üniversite kampüsleri ve sahil yerleşimleriyle bilinen Avcılar, öğrenci taşımacılığından aile evlerine kadar geniş bir yelpazede hizmet gerektiriyor. Ambarlı Limanı çevresinden Denizköşkler sahiline kadar her noktaya hakimiz.",
        "geo_detail": "E-5 ve TEM bağlantılı stratejik konumda, üniversite bölgesi ve sahil yerleşimlerine hızlı erişim.",
        "price_note": "öğrenci ve aile taşıma paketleri mevcut"
    },
    {
        "name": "Bağcılar",
        "slug": "bagcilar-evden-eve-nakliyat",
        "old_file": "ilceler/bagcilar-nakliyat.html",
        "population": "740.000",
        "side": "Avrupa",
        "semtler": ["Güneşli", "Mahmutbey", "Kirazlı", "Yıldıztepe", "Demirkapı"],
        "neighbors": ["Güngören", "Bahçelievler", "Küçükçekmece", "Başakşehir", "Esenler"],
        "neighbor_slugs": ["gungoren-evden-eve-nakliyat", "bahcelievler-evden-eve-nakliyat", "kucukcekmece-evden-eve-nakliyat", "basaksehir-evden-eve-nakliyat", "esenler-evden-eve-nakliyat"],
        "micro_content": "İstanbul'un en kalabalık ilçelerinden Bağcılar, yoğun trafik ve dar sokaklarıyla nakliyat konusunda özel deneyim gerektirir. Güneşli iş merkezlerinden Mahmutbey kavşağına, Kirazlı metro hattı çevresinden Yıldıztepe'nin konut alanlarına kadar bölgeyi avucumuzun içi gibi biliyoruz.",
        "geo_detail": "Yoğun kentsel dokuda, metro hatları ve ana arterler üzerinde deneyimli ekiple hızlı taşıma.",
        "price_note": "dar sokak ve yoğun trafik planlaması dahil"
    },
    {
        "name": "Bahçelievler",
        "slug": "bahcelievler-evden-eve-nakliyat",
        "old_file": "ilceler/bahcelievler-nakliyat.html",
        "population": "600.000",
        "side": "Avrupa",
        "semtler": ["Bahçelievler Merkez", "Şirinevler", "Soğanlı", "Kocasinan", "Yenibosna"],
        "neighbors": ["Bakırköy", "Güngören", "Bağcılar", "Küçükçekmece"],
        "neighbor_slugs": ["bakirkoy-evden-eve-nakliyat", "gungoren-evden-eve-nakliyat", "bagcilar-evden-eve-nakliyat", "kucukcekmece-evden-eve-nakliyat"],
        "micro_content": "Şirinevler metro bağlantısı ve E-5 erişimiyle İstanbul'un ulaşım merkezlerinden biri olan Bahçelievler'de hızlı ve güvenli taşıma hizmeti veriyoruz. Kocasinan'ın geniş bulvarlarından Soğanlı'nın yerleşik mahallelerine kadar her adrese ulaşıyoruz.",
        "geo_detail": "Metro ve E-5 bağlantılı merkezi konumda, apartman ve site taşımacılığında uzman kadro.",
        "price_note": "merkezi konum avantajıyla uygun fiyat"
    },
    {
        "name": "Bakırköy",
        "slug": "bakirkoy-evden-eve-nakliyat",
        "old_file": "ilceler/bakirkoy-nakliyat.html",
        "population": "230.000",
        "side": "Avrupa",
        "semtler": ["Ataköy", "Yeşilköy", "Florya", "Zuhuratbaba", "Osmaniye"],
        "neighbors": ["Bahçelievler", "Güngören", "Zeytinburnu", "Küçükçekmece"],
        "neighbor_slugs": ["bahcelievler-evden-eve-nakliyat", "gungoren-evden-eve-nakliyat", "zeytinburnu-evden-eve-nakliyat", "kucukcekmece-evden-eve-nakliyat"],
        "micro_content": "Ataköy'ün deniz manzaralı rezidanslarından Florya'nın villalarına, Yeşilköy'ün tarihi sokaklarından Zuhuratbaba'nın sakin mahallelerine kadar Bakırköy'ün her köşesini iyi tanıyoruz. Prestijli semtlere özel paketleme ve beyaz eldiven hizmeti sunuyoruz.",
        "geo_detail": "Sahil şeridindeki prestijli semtlerde, lüks konut ve villa taşımacılığında premium hizmet.",
        "price_note": "premium paketleme ve beyaz eldiven hizmeti dahil"
    },
    {
        "name": "Başakşehir",
        "slug": "basaksehir-evden-eve-nakliyat",
        "old_file": "ilceler/basaksehir-nakliyat.html",
        "population": "470.000",
        "side": "Avrupa",
        "semtler": ["Kayabaşı", "Başak Konutları", "Bahçeşehir", "Şahintepe", "Güvercintepe"],
        "neighbors": ["Arnavutköy", "Esenyurt", "Küçükçekmece", "Bağcılar", "Sultangazi"],
        "neighbor_slugs": ["arnavutkoy-evden-eve-nakliyat", "esenyurt-evden-eve-nakliyat", "kucukcekmece-evden-eve-nakliyat", "bagcilar-evden-eve-nakliyat", "sultangazi-evden-eve-nakliyat"],
        "micro_content": "TOKİ konutlarından Bahçeşehir gölet çevresinin lüks villalarına, Kayabaşı'nın dev toplu konutlarından Başak Konutları'nın aile sitelerine kadar Başakşehir'in çok yönlü yapısına hakim ekibimizle hizmetinizdeyiz.",
        "geo_detail": "Toplu konut ve modern site projelerinde deneyimli ekiple, asansörlü taşıma imkanı.",
        "price_note": "site ve toplu konut taşıma uzmanlığı dahil"
    },
    {
        "name": "Bayrampaşa",
        "slug": "bayrampasa-evden-eve-nakliyat",
        "old_file": "ilceler/bayrampasa-nakliyat.html",
        "population": "275.000",
        "side": "Avrupa",
        "semtler": ["Yıldırım", "İsmetpaşa", "Muratpaşa", "Kocatepe", "Altıntepsi"],
        "neighbors": ["Eyüpsultan", "Gaziosmanpaşa", "Esenler", "Güngören", "Zeytinburnu"],
        "neighbor_slugs": ["eyupsultan-evden-eve-nakliyat", "gaziosmanpasa-evden-eve-nakliyat", "esenler-evden-eve-nakliyat", "gungoren-evden-eve-nakliyat", "zeytinburnu-evden-eve-nakliyat"],
        "micro_content": "Forum İstanbul AVM'nin bulunduğu Bayrampaşa, ticari ve konut alanlarının iç içe olduğu bir yapıya sahiptir. Kocatepe'nin yokuş sokaklarından İsmetpaşa'nın ana caddesine kadar bölgenin her köşesini bilen ekibimiz, zorlu adresleriniz için çözüm üretir.",
        "geo_detail": "Merkezi konumda, ticari ve konut bölgelerinde hem ev hem ofis taşıma uzmanlığı.",
        "price_note": "merkezi konum ve kolay erişim avantajı"
    },
    {
        "name": "Beşiktaş",
        "slug": "besiktas-evden-eve-nakliyat",
        "old_file": "ilceler/besiktas-nakliyat.html",
        "population": "185.000",
        "side": "Avrupa",
        "semtler": ["Levent", "Etiler", "Bebek", "Ortaköy", "Arnavutköy Sahil"],
        "neighbors": ["Şişli", "Sarıyer", "Beyoğlu", "Kağıthane"],
        "neighbor_slugs": ["sisli-evden-eve-nakliyat", "sariyer-evden-eve-nakliyat", "beyoglu-evden-eve-nakliyat", "kagithane-evden-eve-nakliyat"],
        "micro_content": "Boğaz'ın en prestijli semtlerini barındıran Beşiktaş'ta, Bebek'in sahil yalılarından Etiler'in lüks rezidanslarına, Levent'in iş kulelerine kadar premium nakliyat hizmeti sunuyoruz. Ortaköy'ün dar tarihî sokaklarında bile sorunsuz taşıma yapıyoruz.",
        "geo_detail": "Boğaz kıyısında prestijli semtlerde, yalı ve rezidans taşımacılığında beyaz eldiven hizmet.",
        "price_note": "lüks konut ve yalı taşıma uzmanlığı dahil"
    },
    {
        "name": "Beykoz",
        "slug": "beykoz-evden-eve-nakliyat",
        "old_file": "ilceler/beykoz-nakliyat.html",
        "population": "250.000",
        "side": "Anadolu",
        "semtler": ["Kavacık", "Anadoluhisarı", "Çubuklu", "Paşabahçe", "Riva"],
        "neighbors": ["Üsküdar", "Çekmeköy", "Şile", "Sancaktepe"],
        "neighbor_slugs": ["uskudar-evden-eve-nakliyat", "cekmekoy-evden-eve-nakliyat", "sile-evden-eve-nakliyat", "sancaktepe-evden-eve-nakliyat"],
        "micro_content": "Boğaz'ın Anadolu yakasındaki yeşil cenneti Beykoz'da, Kavacık'ın modern iş merkezlerinden Anadoluhisarı'nın tarihî yalılarına, Riva'nın sakin köy evlerinden Çubuklu'nun villaları na kadar özenli taşıma hizmeti veriyoruz.",
        "geo_detail": "Doğa ile iç içe bölgede, villa ve müstakil ev taşımacılığında uzman kadro.",
        "price_note": "villa ve müstakil ev taşıma uzmanlığı dahil"
    },
    {
        "name": "Beylikdüzü",
        "slug": "beylikduzu-evden-eve-nakliyat",
        "old_file": "ilceler/beylikduzu-nakliyat.html",
        "population": "360.000",
        "side": "Avrupa",
        "semtler": ["Yakuplu", "Büyükşehir", "Adnan Kahveci", "Kavakli", "Sahil"],
        "neighbors": ["Avcılar", "Esenyurt", "Büyükçekmece"],
        "neighbor_slugs": ["avcilar-evden-eve-nakliyat", "esenyurt-evden-eve-nakliyat", "buyukcekmece-evden-eve-nakliyat"],
        "micro_content": "Planlı kentleşmenin örneği Beylikdüzü, geniş bulvarları ve modern siteleriyle taşınma sürecini kolaylaştırıyor. Yakuplu'nun sanayi bölgesinden Sahil'in deniz manzaralı konutlarına, Büyükşehir mahallelerinin aile sitelerine kadar hızlı ve düzenli taşıma yapıyoruz.",
        "geo_detail": "Planlı şehirleşme bölgesinde, geniş yollar ve modern altyapı ile hızlı taşıma imkanı.",
        "price_note": "modern site ve konut taşıma kolaylığı"
    },
    {
        "name": "Beyoğlu",
        "slug": "beyoglu-evden-eve-nakliyat",
        "old_file": "ilceler/beyoglu-nakliyat.html",
        "population": "230.000",
        "side": "Avrupa",
        "semtler": ["Taksim", "Cihangir", "Galata", "Karaköy", "Tarlabaşı"],
        "neighbors": ["Şişli", "Beşiktaş", "Fatih", "Kağıthane"],
        "neighbor_slugs": ["sisli-evden-eve-nakliyat", "besiktas-evden-eve-nakliyat", "fatih-evden-eve-nakliyat", "kagithane-evden-eve-nakliyat"],
        "micro_content": "İstanbul'un kalbi Beyoğlu'nda, İstiklal Caddesi'nin arka sokaklarından Cihangir'in merdiven sokaklarına, Galata Kulesi çevresinden Karaköy'ün dönüşen depo binalarına kadar tarihî dokuya saygılı, özenli nakliyat hizmeti veriyoruz.",
        "geo_detail": "Tarihî yarımada ve dar sokak yapısında, portatif ekipman ve deneyimli ekiple hassas taşıma.",
        "price_note": "dar sokak ve tarihî bina uzmanlığı dahil"
    },
    {
        "name": "Büyükçekmece",
        "slug": "buyukcekmece-evden-eve-nakliyat",
        "old_file": "ilceler/buyukcekmece-nakliyat.html",
        "population": "260.000",
        "side": "Avrupa",
        "semtler": ["Mimarsinan", "Kumburgaz", "Karaağaç", "Türkoba", "Pınartepe"],
        "neighbors": ["Beylikdüzü", "Çatalca", "Silivri", "Esenyurt"],
        "neighbor_slugs": ["beylikduzu-evden-eve-nakliyat", "catalca-evden-eve-nakliyat", "silivri-evden-eve-nakliyat", "esenyurt-evden-eve-nakliyat"],
        "micro_content": "Göl manzarası ve sahil şeridiyle İstanbul'un batı kapısı Büyükçekmece'de, Kumburgaz'ın yazlık sitelerinden Mimarsinan'ın yeni konut projelerine kadar mevsimsel ve kalıcı taşıma hizmeti sunuyoruz.",
        "geo_detail": "Göl ve sahil çevresinde, yazlık-kışlık ev taşıma ve mevsimsel depolama hizmeti.",
        "price_note": "mevsimsel taşıma ve depolama seçenekleri mevcut"
    },
    {
        "name": "Çatalca",
        "slug": "catalca-evden-eve-nakliyat",
        "old_file": "ilceler/catalca-nakliyat.html",
        "population": "75.000",
        "side": "Avrupa",
        "semtler": ["Çatalca Merkez", "Ferhatpaşa", "Kestanelik", "Kaleiçi", "Elbasan"],
        "neighbors": ["Arnavutköy", "Büyükçekmece", "Silivri"],
        "neighbor_slugs": ["arnavutkoy-evden-eve-nakliyat", "buyukcekmece-evden-eve-nakliyat", "silivri-evden-eve-nakliyat"],
        "micro_content": "İstanbul'un en geniş yüzölçümüne sahip Çatalca, kırsal yapısı ve çiftlik evleriyle farklı bir nakliyat deneyimi sunar. Merkez'in tarihi sokaklarından köy yerleşimlerine kadar büyük araç filosuyla her noktaya ulaşıyoruz.",
        "geo_detail": "Kırsal ve yarı kırsal bölgede, geniş araç filosuyla uzak mesafe taşımacılığı.",
        "price_note": "uzak mesafe ve kırsal erişim planlaması dahil"
    },
    {
        "name": "Çekmeköy",
        "slug": "cekmekoy-evden-eve-nakliyat",
        "old_file": "ilceler/cekmekoy-nakliyat.html",
        "population": "260.000",
        "side": "Anadolu",
        "semtler": ["Çekmeköy Merkez", "Alemdağ", "Taşdelen", "Ömerli", "Hamidiye"],
        "neighbors": ["Ümraniye", "Sancaktepe", "Beykoz", "Şile"],
        "neighbor_slugs": ["umraniye-evden-eve-nakliyat", "sancaktepe-evden-eve-nakliyat", "beykoz-evden-eve-nakliyat", "sile-evden-eve-nakliyat"],
        "micro_content": "Ormanları ve yeşil alanlarıyla Anadolu yakasının nefes aldığı Çekmeköy'de, Alemdağ'ın villaları ndan Taşdelen'in site konutlarına, Ömerli Barajı çevresinin sakin yaşam alanlarına kadar doğaya duyarlı taşıma hizmeti veriyoruz.",
        "geo_detail": "Yeşil alan ve orman bölgesinde, villa ve site taşımacılığında özel ekipman desteği.",
        "price_note": "villa ve bahçeli ev taşıma uzmanlığı dahil"
    },
    {
        "name": "Esenler",
        "slug": "esenler-evden-eve-nakliyat",
        "old_file": "ilceler/esenler-nakliyat.html",
        "population": "450.000",
        "side": "Avrupa",
        "semtler": ["Menderes", "Oruçreis", "Davutpaşa", "Fatih", "Birlik"],
        "neighbors": ["Bağcılar", "Bayrampaşa", "Güngören", "Sultangazi", "Gaziosmanpaşa"],
        "neighbor_slugs": ["bagcilar-evden-eve-nakliyat", "bayrampasa-evden-eve-nakliyat", "gungoren-evden-eve-nakliyat", "sultangazi-evden-eve-nakliyat", "gaziosmanpasa-evden-eve-nakliyat"],
        "micro_content": "Otogar'ın bulunduğu Esenler, İstanbul'un ulaşım merkezi olma özelliğiyle nakliyat açısından stratejik bir konumdadır. Menderes'in kalabalık sokaklarından Davutpaşa'nın üniversite çevresine kadar hızlı ve ekonomik taşıma çözümleri sunuyoruz.",
        "geo_detail": "Otogar bağlantılı merkezi konumda, ekonomik ve hızlı şehir içi taşıma çözümleri.",
        "price_note": "merkezi konum ve ekonomik fiyat avantajı"
    },
    {
        "name": "Esenyurt",
        "slug": "esenyurt-evden-eve-nakliyat",
        "old_file": "ilceler/esenyurt-nakliyat.html",
        "population": "960.000",
        "side": "Avrupa",
        "semtler": ["Kıraç", "Ardıçlı", "Fatih", "Yenikent", "Saadetdere"],
        "neighbors": ["Avcılar", "Beylikdüzü", "Büyükçekmece", "Başakşehir", "Arnavutköy"],
        "neighbor_slugs": ["avcilar-evden-eve-nakliyat", "beylikduzu-evden-eve-nakliyat", "buyukcekmece-evden-eve-nakliyat", "basaksehir-evden-eve-nakliyat", "arnavutkoy-evden-eve-nakliyat"],
        "micro_content": "İstanbul'un en kalabalık ilçesi Esenyurt'ta, Kıraç sanayi bölgesinden Yenikent'in yeni sitelerine, Saadetdere'nin aile konutlarından Ardıçlı'nın toplu taşıma hattı çevresine kadar yüksek yoğunluklu bölgelerde deneyimli ekibimizle hizmet veriyoruz.",
        "geo_detail": "Yüksek nüfus yoğunluğunda, çok katlı bina ve site taşımacılığında geniş araç filosu.",
        "price_note": "yüksek yoğunluk bölgesinde rekabetçi fiyat"
    },
    {
        "name": "Eyüpsultan",
        "slug": "eyupsultan-evden-eve-nakliyat",
        "old_file": "ilceler/eyupsultan-nakliyat.html",
        "population": "400.000",
        "side": "Avrupa",
        "semtler": ["Alibeyköy", "Rami", "Göktürk", "Kemerburgaz", "Pirinççi"],
        "neighbors": ["Kağıthane", "Bayrampaşa", "Gaziosmanpaşa", "Arnavutköy", "Sarıyer"],
        "neighbor_slugs": ["kagithane-evden-eve-nakliyat", "bayrampasa-evden-eve-nakliyat", "gaziosmanpasa-evden-eve-nakliyat", "arnavutkoy-evden-eve-nakliyat", "sariyer-evden-eve-nakliyat"],
        "micro_content": "Tarihi dokusu ile modern yaşamın buluştuğu Eyüpsultan'da, Göktürk'ün lüks villalarından Alibeyköy'ün konut alanlarına, Kemerburgaz'ın orman evlerinden Rami'nin ticari bölgesine kadar çok yönlü nakliyat hizmeti sunuyoruz.",
        "geo_detail": "Tarihi ve modern bölgelerin buluştuğu ilçede, villa ve apartman taşımacılığında uzman kadro.",
        "price_note": "villa ve tarihî bina taşıma uzmanlığı dahil"
    },
    {
        "name": "Fatih",
        "slug": "fatih-evden-eve-nakliyat",
        "old_file": "ilceler/fatih-nakliyat.html",
        "population": "440.000",
        "side": "Avrupa",
        "semtler": ["Aksaray", "Laleli", "Sultanahmet", "Fener", "Balat", "Vefa"],
        "neighbors": ["Beyoğlu", "Zeytinburnu", "Bayrampaşa", "Eyüpsultan"],
        "neighbor_slugs": ["beyoglu-evden-eve-nakliyat", "zeytinburnu-evden-eve-nakliyat", "bayrampasa-evden-eve-nakliyat", "eyupsultan-evden-eve-nakliyat"],
        "micro_content": "Tarihi yarımadanın kalbindeki Fatih'te, Sultanahmet'in koruma altındaki binalarından Balat'ın renkli sokaklarına, Aksaray'ın yoğun trafiğinden Vefa'nın sakin mahallelerine kadar tarihî dokuya zarar vermeden özenli taşıma yapıyoruz.",
        "geo_detail": "Tarihi yarımadada, koruma altındaki binalarda özel ekipman ve dikkatli taşıma hizmeti.",
        "price_note": "tarihî bina ve dar sokak uzmanlığı dahil"
    },
    {
        "name": "Gaziosmanpaşa",
        "slug": "gaziosmanpasa-evden-eve-nakliyat",
        "old_file": "ilceler/gaziosmanpasa-nakliyat.html",
        "population": "500.000",
        "side": "Avrupa",
        "semtler": ["Küçükköy", "Bağlarbaşı", "Karlıtepe", "Yıldıztabya", "Merkez"],
        "neighbors": ["Eyüpsultan", "Sultangazi", "Bayrampaşa", "Esenler"],
        "neighbor_slugs": ["eyupsultan-evden-eve-nakliyat", "sultangazi-evden-eve-nakliyat", "bayrampasa-evden-eve-nakliyat", "esenler-evden-eve-nakliyat"],
        "micro_content": "Kentsel dönüşümün hız kazandığı Gaziosmanpaşa'da, yeni konut projelerine taşınma taleplerinde büyük artış yaşanıyor. Küçükköy'ün yenilenen mahallelerinden Karlıtepe'nin dönüşüm projelerine kadar güvenli ve hızlı taşıma çözümleri sunuyoruz.",
        "geo_detail": "Kentsel dönüşüm bölgesinde, yeni konut projelerine taşınma konusunda uzman ekip.",
        "price_note": "kentsel dönüşüm taşıma deneyimi dahil"
    },
    {
        "name": "Güngören",
        "slug": "gungoren-evden-eve-nakliyat",
        "old_file": "ilceler/gungoren-nakliyat.html",
        "population": "290.000",
        "side": "Avrupa",
        "semtler": ["Merkez", "Güneştepe", "Sanayi", "Tozkoparan", "Haznedar"],
        "neighbors": ["Bahçelievler", "Bağcılar", "Esenler", "Bayrampaşa", "Zeytinburnu"],
        "neighbor_slugs": ["bahcelievler-evden-eve-nakliyat", "bagcilar-evden-eve-nakliyat", "esenler-evden-eve-nakliyat", "bayrampasa-evden-eve-nakliyat", "zeytinburnu-evden-eve-nakliyat"],
        "micro_content": "İstanbul'un en küçük ilçelerinden Güngören, kompakt yapısıyla taşıma sürecinde dikkatli planlama gerektirir. Tozkoparan'ın toplu konut bloklarından Haznedar'ın iş merkezlerine, Sanayi Mahallesi'nin ticari alanlarından Güneştepe'nin konut dokusuna kadar her noktaya hakimiz.",
        "geo_detail": "Kompakt ilçe yapısında, kısa mesafeli ve hızlı ev-ofis taşıma hizmeti.",
        "price_note": "kısa mesafe avantajıyla ekonomik fiyat"
    },
    {
        "name": "Kadıköy",
        "slug": "kadikoy-evden-eve-nakliyat",
        "old_file": "ilceler/kadikoy-nakliyat.html",
        "population": "480.000",
        "side": "Anadolu",
        "semtler": ["Moda", "Caddebostan", "Bağdat Caddesi", "Fenerbahçe", "Göztepe", "Erenköy"],
        "neighbors": ["Ataşehir", "Maltepe", "Üsküdar"],
        "neighbor_slugs": ["atasehir-evden-eve-nakliyat", "maltepe-evden-eve-nakliyat", "uskudar-evden-eve-nakliyat"],
        "micro_content": "Moda'nın dar arnavut kaldırımlı sokaklarından Bağdat Caddesi'nin trafiğine, Caddebostan sahilinden Fenerbahçe'nin sakin konut alanlarına kadar Kadıköy'ün her köşesine hakimiz. Anadolu yakasının en gözde ilçesinde premium nakliyat deneyimi sunuyoruz.",
        "geo_detail": "Anadolu yakasının merkezinde, sahil ve prestijli semtlere özel taşıma hizmeti.",
        "price_note": "prestijli semt uzmanlığı ve premium paketleme dahil"
    },
    {
        "name": "Kağıthane",
        "slug": "kagithane-evden-eve-nakliyat",
        "old_file": "ilceler/kagithane-nakliyat.html",
        "population": "450.000",
        "side": "Avrupa",
        "semtler": ["Çeliktepe", "Seyrantepe", "Hürriyet", "Nurtepe", "Hamidiye"],
        "neighbors": ["Şişli", "Beşiktaş", "Eyüpsultan", "Beyoğlu", "Sarıyer"],
        "neighbor_slugs": ["sisli-evden-eve-nakliyat", "besiktas-evden-eve-nakliyat", "eyupsultan-evden-eve-nakliyat", "beyoglu-evden-eve-nakliyat", "sariyer-evden-eve-nakliyat"],
        "micro_content": "Hızla dönüşen Kağıthane'de, Seyrantepe'nin yeni iş kulelerinden Çeliktepe'nin geleneksel mahallelerine, Hürriyet tepelerinin manzaralı konutlarından Nurtepe'nin kentsel dönüşüm alanlarına kadar profesyonel taşıma hizmeti veriyoruz.",
        "geo_detail": "Kentsel dönüşüm ve yeni iş merkezi bölgesinde, modern bina taşımacılığında uzman kadro.",
        "price_note": "kentsel dönüşüm ve yeni bina taşıma uzmanlığı dahil"
    },
    {
        "name": "Kartal",
        "slug": "kartal-evden-eve-nakliyat",
        "old_file": "ilceler/kartal-nakliyat.html",
        "population": "470.000",
        "side": "Anadolu",
        "semtler": ["Kordonboyu", "Soğanlık", "Yakacık", "Uğur Mumcu", "Hürriyet"],
        "neighbors": ["Maltepe", "Pendik", "Sultanbeyli", "Sancaktepe"],
        "neighbor_slugs": ["maltepe-evden-eve-nakliyat", "pendik-evden-eve-nakliyat", "sultanbeyli-evden-eve-nakliyat", "sancaktepe-evden-eve-nakliyat"],
        "micro_content": "Anadolu yakasının yükselen yıldızı Kartal'da, Kordonboyu sahilinin lüks projelerinden Soğanlık'ın yerleşik mahallelerine, Yakacık'ın geniş konut alanlarından Hürriyet'in yeni sitelerine kadar her türlü taşıma ihtiyacınızı karşılıyoruz.",
        "geo_detail": "Sahil ve iç kesim bölgelerinde, hem lüks proje hem konut taşımacılığı.",
        "price_note": "sahil ve iç kesim taşıma uzmanlığı dahil"
    },
    {
        "name": "Küçükçekmece",
        "slug": "kucukcekmece-evden-eve-nakliyat",
        "old_file": "ilceler/kucukcekmece-nakliyat.html",
        "population": "790.000",
        "side": "Avrupa",
        "semtler": ["Halkalı", "Sefaköy", "Cennet", "İnönü", "Atakent"],
        "neighbors": ["Avcılar", "Bağcılar", "Bahçelievler", "Başakşehir", "Bakırköy"],
        "neighbor_slugs": ["avcilar-evden-eve-nakliyat", "bagcilar-evden-eve-nakliyat", "bahcelievler-evden-eve-nakliyat", "basaksehir-evden-eve-nakliyat", "bakirkoy-evden-eve-nakliyat"],
        "micro_content": "Halkalı tren istasyonuyla İstanbul'un batı kapısı olan Küçükçekmece'de, Atakent'in toplu konut bloklarından Sefaköy'ün ticari merkezine, Cennet Mahallesi'nin aile sitelerinden göl çevresinin konut projelerine kadar geniş bir alanda hizmet veriyoruz.",
        "geo_detail": "Marmaray ve tren bağlantılı stratejik konumda, toplu konut ve site taşımacılığı.",
        "price_note": "toplu konut ve site taşıma uzmanlığı dahil"
    },
    {
        "name": "Maltepe",
        "slug": "maltepe-evden-eve-nakliyat",
        "old_file": "ilceler/maltepe-nakliyat.html",
        "population": "510.000",
        "side": "Anadolu",
        "semtler": ["Bağlarbaşı", "Cevizli", "Küçükyalı", "Altayçeşme", "İdealtepe"],
        "neighbors": ["Kadıköy", "Ataşehir", "Kartal", "Sancaktepe"],
        "neighbor_slugs": ["kadikoy-evden-eve-nakliyat", "atasehir-evden-eve-nakliyat", "kartal-evden-eve-nakliyat", "sancaktepe-evden-eve-nakliyat"],
        "micro_content": "Sahil dolgu alanları ve iç kesimdeki yerleşik mahalleleriyle Maltepe, Anadolu yakasının büyüyen ilçesidir. Küçükyalı sahilinden İdealtepe'nin manzaralı tepelerine, Cevizli'nin modern sitelerinden Bağlarbaşı'nın geleneksel konutlarına kadar her adrese ulaşıyoruz.",
        "geo_detail": "Sahil ve tepe yerleşimlerinde, çok katlı bina ve müstakil ev taşımacılığı.",
        "price_note": "sahil ve tepe bölgesi taşıma planlaması dahil"
    },
    {
        "name": "Pendik",
        "slug": "pendik-evden-eve-nakliyat",
        "old_file": "ilceler/pendik-nakliyat.html",
        "population": "700.000",
        "side": "Anadolu",
        "semtler": ["Kaynarca", "Yenişehir", "Kurtköy", "Güzelyalı", "Velibaba"],
        "neighbors": ["Kartal", "Sultanbeyli", "Tuzla", "Çekmeköy", "Sancaktepe"],
        "neighbor_slugs": ["kartal-evden-eve-nakliyat", "sultanbeyli-evden-eve-nakliyat", "tuzla-evden-eve-nakliyat", "cekmekoy-evden-eve-nakliyat", "sancaktepe-evden-eve-nakliyat"],
        "micro_content": "Sabiha Gökçen Havalimanı'nın bulunduğu Pendik, ulaşım kolaylığıyla taşınma sürecini hızlandırır. Kurtköy'ün yeni yerleşim alanlarından Kaynarca'nın yoğun konut bölgesine, Güzelyalı sahilinden Yenişehir'in modern sitelerine kadar profesyonel hizmet sunuyoruz.",
        "geo_detail": "Havalimanı bağlantılı stratejik konumda, yeni yerleşim ve site taşımacılığı.",
        "price_note": "havalimanı bölgesi erişim kolaylığı"
    },
    {
        "name": "Sancaktepe",
        "slug": "sancaktepe-evden-eve-nakliyat",
        "old_file": "ilceler/sancaktepe-nakliyat.html",
        "population": "420.000",
        "side": "Anadolu",
        "semtler": ["Samandıra", "Sarıgazi", "Yenidoğan", "Abdurrahman Gazi", "Meclis"],
        "neighbors": ["Ümraniye", "Çekmeköy", "Kartal", "Pendik", "Sultanbeyli", "Ataşehir"],
        "neighbor_slugs": ["umraniye-evden-eve-nakliyat", "cekmekoy-evden-eve-nakliyat", "kartal-evden-eve-nakliyat", "pendik-evden-eve-nakliyat", "sultanbeyli-evden-eve-nakliyat", "atasehir-evden-eve-nakliyat"],
        "micro_content": "Hızla gelişen Sancaktepe'de, Samandıra'nın askeri bölge yakınındaki yerleşimlerden Sarıgazi'nin kalabalık mahallelerine, Yenidoğan'ın yeni konut projelerinden Meclis Mahallesi'nin aile sitelerine kadar büyüyen talebi karşılıyoruz.",
        "geo_detail": "Gelişen bölgede, yeni konut projeleri ve toplu konut taşımacılığında uzman ekip.",
        "price_note": "gelişen bölge avantajıyla rekabetçi fiyat"
    },
    {
        "name": "Sarıyer",
        "slug": "sariyer-evden-eve-nakliyat",
        "old_file": "ilceler/sariyer-nakliyat.html",
        "population": "350.000",
        "side": "Avrupa",
        "semtler": ["Maslak", "İstinye", "Tarabya", "Emirgan", "Rumelihisarı"],
        "neighbors": ["Beşiktaş", "Eyüpsultan", "Kağıthane"],
        "neighbor_slugs": ["besiktas-evden-eve-nakliyat", "eyupsultan-evden-eve-nakliyat", "kagithane-evden-eve-nakliyat"],
        "micro_content": "Boğaz'ın en zarif semtlerini barındıran Sarıyer'de, Maslak'ın iş kulelerinden İstinye'nin sahil yalılarına, Tarabya'nın tarihi konaklarından Emirgan'ın koruluklarına kadar özenli ve prestijli taşıma hizmeti sunuyoruz.",
        "geo_detail": "Boğaz kıyısında, yalı ve lüks villa taşımacılığında beyaz eldiven premium hizmet.",
        "price_note": "lüks konut ve yalı taşıma premium paketi dahil"
    },
    {
        "name": "Silivri",
        "slug": "silivri-evden-eve-nakliyat",
        "old_file": "ilceler/silivri-nakliyat.html",
        "population": "200.000",
        "side": "Avrupa",
        "semtler": ["Silivri Merkez", "Selimpaşa", "Gümüşyaka", "Kavaklı", "Ortaköy"],
        "neighbors": ["Büyükçekmece", "Çatalca"],
        "neighbor_slugs": ["buyukcekmece-evden-eve-nakliyat", "catalca-evden-eve-nakliyat"],
        "micro_content": "İstanbul'un en batısında yer alan Silivri, yazlık siteleri ve sakin yaşam alanlarıyla bilinir. Selimpaşa sahilinden Gümüşyaka'nın tatil sitelerine, Merkez'in yerleşik konutlarından Kavaklı'nın kırsal alanlarına kadar mevsimsel ve kalıcı taşıma hizmeti veriyoruz.",
        "geo_detail": "İstanbul'un batı ucunda, yazlık ve kalıcı konut taşımacılığında uzman lojistik.",
        "price_note": "uzak mesafe ve mevsimsel taşıma planlaması dahil"
    },
    {
        "name": "Sultanbeyli",
        "slug": "sultanbeyli-evden-eve-nakliyat",
        "old_file": "ilceler/sultanbeyli-nakliyat.html",
        "population": "330.000",
        "side": "Anadolu",
        "semtler": ["Merkez", "Battalgazi", "Necip Fazıl", "Hasanpaşa", "Mehmet Akif"],
        "neighbors": ["Kartal", "Pendik", "Sancaktepe", "Çekmeköy"],
        "neighbor_slugs": ["kartal-evden-eve-nakliyat", "pendik-evden-eve-nakliyat", "sancaktepe-evden-eve-nakliyat", "cekmekoy-evden-eve-nakliyat"],
        "micro_content": "Kentsel dönüşümle yenilenen Sultanbeyli'de, Battalgazi'nin yeni konut projelerinden Mehmet Akif'in aile sitelerine, Merkez'in canlı ticaret alanlarından Hasanpaşa'nın sakin mahallelerine kadar her noktaya güvenle ulaşıyoruz.",
        "geo_detail": "Kentsel dönüşüm bölgesinde, yeni bina ve konut projeleri taşımacılığında deneyimli ekip.",
        "price_note": "kentsel dönüşüm taşıma uzmanlığı dahil"
    },
    {
        "name": "Sultangazi",
        "slug": "sultangazi-evden-eve-nakliyat",
        "old_file": "ilceler/sultangazi-nakliyat.html",
        "population": "530.000",
        "side": "Avrupa",
        "semtler": ["Cebeci", "Esentepe", "Malkoçoğlu", "Zübeyde Hanım", "50. Yıl"],
        "neighbors": ["Gaziosmanpaşa", "Eyüpsultan", "Arnavutköy", "Başakşehir", "Esenler"],
        "neighbor_slugs": ["gaziosmanpasa-evden-eve-nakliyat", "eyupsultan-evden-eve-nakliyat", "arnavutkoy-evden-eve-nakliyat", "basaksehir-evden-eve-nakliyat", "esenler-evden-eve-nakliyat"],
        "micro_content": "İstanbul'un genç nüfuslu ilçelerinden Sultangazi, yoğun konut dokusuyla hızlı ve düzenli taşıma hizmeti gerektirir. Cebeci'nin geniş caddelerinden Esentepe'nin toplu konutlarına, Malkoçoğlu'nun aile mahallelerinden 50. Yıl'ın site alanlarına kadar tüm bölgede hizmetinizdeyiz.",
        "geo_detail": "Yoğun konut bölgesinde, apartman ve toplu konut taşımacılığında hızlı çözümler.",
        "price_note": "toplu konut taşıma deneyimi ve ekonomik fiyat"
    },
    {
        "name": "Şile",
        "slug": "sile-evden-eve-nakliyat",
        "old_file": "ilceler/sile-nakliyat.html",
        "population": "40.000",
        "side": "Anadolu",
        "semtler": ["Şile Merkez", "Ağva", "Kumbaba", "Doğancılı", "Sahilköy"],
        "neighbors": ["Beykoz", "Çekmeköy", "Pendik"],
        "neighbor_slugs": ["beykoz-evden-eve-nakliyat", "cekmekoy-evden-eve-nakliyat", "pendik-evden-eve-nakliyat"],
        "micro_content": "Karadeniz kıyısındaki sakin tatil beldesi Şile, yazlık ev ve butik otel taşımacılığıyla öne çıkıyor. Ağva'nın nehir kenarı evlerinden Kumbaba sahilinin yazlıklarına, Merkez'in geleneksel taş evlerinden Doğancılı'nın kırsal villalarına kadar özel lojistik planlama yapıyoruz.",
        "geo_detail": "Karadeniz kıyısında, yazlık ve kırsal ev taşımacılığında özel lojistik planlama.",
        "price_note": "uzak mesafe ve kırsal erişim lojistiği dahil"
    },
    {
        "name": "Şişli",
        "slug": "sisli-evden-eve-nakliyat",
        "old_file": "ilceler/sisli-nakliyat.html",
        "population": "330.000",
        "side": "Avrupa",
        "semtler": ["Mecidiyeköy", "Nişantaşı", "Osmanbey", "Bomonti", "Fulya"],
        "neighbors": ["Beşiktaş", "Beyoğlu", "Kağıthane", "Sarıyer"],
        "neighbor_slugs": ["besiktas-evden-eve-nakliyat", "beyoglu-evden-eve-nakliyat", "kagithane-evden-eve-nakliyat", "sariyer-evden-eve-nakliyat"],
        "micro_content": "İstanbul'un ticaret ve moda merkezi Şişli'de, Nişantaşı'nın lüks butik sokaklarından Mecidiyeköy'ün iş kulelerine, Bomonti'nin dönüşen fabrika binalarından Fulya'nın modern rezidanslarına kadar premium nakliyat hizmeti sunuyoruz.",
        "geo_detail": "İş ve ticaret merkezinde, ofis ve lüks konut taşımacılığında premium hizmet.",
        "price_note": "merkezi iş bölgesi ve lüks konut uzmanlığı dahil"
    },
    {
        "name": "Tuzla",
        "slug": "tuzla-evden-eve-nakliyat",
        "old_file": "ilceler/tuzla-nakliyat.html",
        "population": "270.000",
        "side": "Anadolu",
        "semtler": ["Tuzla Merkez", "Aydınlı", "Şifa", "İçmeler", "Orhanlı"],
        "neighbors": ["Pendik", "Kartal", "Sultanbeyli"],
        "neighbor_slugs": ["pendik-evden-eve-nakliyat", "kartal-evden-eve-nakliyat", "sultanbeyli-evden-eve-nakliyat"],
        "micro_content": "Tersaneler bölgesi ve sanayi tesisleriyle bilinen Tuzla, aynı zamanda İçmeler'in şifalı kaplıcaları ve Aydınlı'nın modern siteleriyle de dikkat çeker. Orhanlı sanayi bölgesinden Şifa'nın sakin konutlarına kadar hem ev hem ofis taşımacılığında uzmanız.",
        "geo_detail": "Sanayi ve konut bölgelerinin bir arada olduğu ilçede, hem ev hem ofis taşımacılığı.",
        "price_note": "sanayi bölgesi ve konut taşıma uzmanlığı dahil"
    },
    {
        "name": "Ümraniye",
        "slug": "umraniye-evden-eve-nakliyat",
        "old_file": "ilceler/umraniye-nakliyat.html",
        "population": "700.000",
        "side": "Anadolu",
        "semtler": ["Çakmak", "Atatürk", "Hekimbaşı", "Tantavi", "Parseller"],
        "neighbors": ["Üsküdar", "Ataşehir", "Sancaktepe", "Çekmeköy", "Beykoz"],
        "neighbor_slugs": ["uskudar-evden-eve-nakliyat", "atasehir-evden-eve-nakliyat", "sancaktepe-evden-eve-nakliyat", "cekmekoy-evden-eve-nakliyat", "beykoz-evden-eve-nakliyat"],
        "micro_content": "Anadolu yakasının en hızlı büyüyen ilçelerinden Ümraniye'de, Çakmak'ın yoğun ticaret alanlarından Hekimbaşı'nın yeni sitelerine, Tantavi'nin kentsel dönüşüm projelerinden Atatürk Mahallesi'nin yerleşik konutlarına kadar geniş kapsamlı nakliyat hizmeti veriyoruz.",
        "geo_detail": "Hızla büyüyen bölgede, site ve toplu konut taşımacılığında geniş araç filosu.",
        "price_note": "büyüyen bölge ve toplu konut taşıma uzmanlığı dahil"
    },
    {
        "name": "Üsküdar",
        "slug": "uskudar-evden-eve-nakliyat",
        "old_file": "ilceler/uskudar-nakliyat.html",
        "population": "540.000",
        "side": "Anadolu",
        "semtler": ["Çengelköy", "Kuzguncuk", "Beylerbeyi", "Acıbadem", "Altunizade"],
        "neighbors": ["Kadıköy", "Ümraniye", "Beykoz", "Ataşehir"],
        "neighbor_slugs": ["kadikoy-evden-eve-nakliyat", "umraniye-evden-eve-nakliyat", "beykoz-evden-eve-nakliyat", "atasehir-evden-eve-nakliyat"],
        "micro_content": "Boğaz'ın Anadolu yakasındaki tarihi mücevheri Üsküdar'da, Kuzguncuk'un renkli ahşap evlerinden Çengelköy'ün çınar altı meydanına, Beylerbeyi Sarayı çevresinin yalılarından Altunizade'nin modern iş merkezlerine kadar özenli taşıma hizmeti sunuyoruz.",
        "geo_detail": "Boğaz kıyısında tarihi ve modern dokuyu bir arada barındıran ilçede, premium taşıma hizmeti.",
        "price_note": "tarihî semt ve Boğaz kıyısı taşıma uzmanlığı dahil"
    },
    {
        "name": "Zeytinburnu",
        "slug": "zeytinburnu-evden-eve-nakliyat",
        "old_file": "ilceler/zeytinburnu-nakliyat.html",
        "population": "290.000",
        "side": "Avrupa",
        "semtler": ["Kazlıçeşme", "Merkezefendi", "Beştelsiz", "Sümer", "Veliefendi"],
        "neighbors": ["Fatih", "Bayrampaşa", "Güngören", "Bakırköy"],
        "neighbor_slugs": ["fatih-evden-eve-nakliyat", "bayrampasa-evden-eve-nakliyat", "gungoren-evden-eve-nakliyat", "bakirkoy-evden-eve-nakliyat"],
        "micro_content": "Kentsel dönüşümle tamamen yenilenen Zeytinburnu'nda, Kazlıçeşme'nin sahil projelerinden Merkezefendi'nin modern konutlarına, Veliefendi Hipodromu çevresinin yeni yapılarından Sümer'in aile mahallelerine kadar yenilenen İstanbul'un temsilcisi olarak hizmet veriyoruz.",
        "geo_detail": "Kentsel dönüşüm tamamlanmış bölgede, yeni bina ve modern konut taşımacılığı.",
        "price_note": "yeni bina ve modern konut taşıma deneyimi dahil"
    }
]

# Hizmet Silosu verileri
SERVICES = [
    {
        "name": "İstanbul Evden Eve Nakliyat",
        "slug": "istanbul-evden-eve-nakliyat",
        "meta_title": "İstanbul Evden Eve Nakliyat - Taşyol Nakliyat | Sigortalı Taşıma",
        "meta_desc": "İstanbul evden eve nakliyat hizmeti. Sigortalı, profesyonel, sabit fiyat garantili. 7/24 WhatsApp destek. Ücretsiz keşif ve teklif alın.",
        "h1": "İstanbul Evden Eve Nakliyat",
        "icon": "fa-house-chimney",
        "is_pillar": True
    },
    {
        "name": "Ofis ve İşyeri Taşımacılığı",
        "slug": "ofis-ve-isyeri-tasimaciligi",
        "meta_title": "İstanbul Ofis Taşıma - Taşyol Nakliyat | İşyeri Taşımacılığı",
        "meta_desc": "İstanbul ofis ve işyeri taşıma hizmeti. Hafta sonu taşıma, IT ekipman koruması, minimum iş kaybı. Profesyonel ofis taşımacılığı.",
        "h1": "Ofis ve İşyeri Taşımacılığı",
        "icon": "fa-building",
        "is_pillar": False
    },
    {
        "name": "Asansörlü Nakliyat",
        "slug": "asansorlu-nakliyat",
        "meta_title": "Asansörlü Nakliyat İstanbul - Taşyol Nakliyat | Dış Cephe Asansörü",
        "meta_desc": "İstanbul asansörlü nakliyat hizmeti. Yüksek katlı binalarda dış cephe asansörü ile hızlı ve güvenli eşya taşıma. Ücretsiz keşif.",
        "h1": "Asansörlü Nakliyat Hizmeti",
        "icon": "fa-elevator",
        "is_pillar": False
    },
    {
        "name": "Şehir İçi Kamyonet Nakliye",
        "slug": "sehir-ici-kamyonet-nakliye",
        "meta_title": "Şehir İçi Kamyonet Nakliye İstanbul - Taşyol Nakliyat",
        "meta_desc": "İstanbul şehir içi kamyonet nakliye hizmeti. Dar sokak çözümü, hızlı teslimat, ekonomik fiyat. Küçük taşımalar için ideal.",
        "h1": "Şehir İçi Kamyonet Nakliye",
        "icon": "fa-truck-pickup",
        "is_pillar": False
    }
]

if __name__ == "__main__":
    print(f"Toplam {len(DISTRICTS)} ilçe verisi hazır.")
    for d in DISTRICTS:
        print(f"  {d['name']} → /bolgeler/{d['slug']}.html")
    print(f"\nToplam {len(SERVICES)} hizmet sayfası planlandı.")
    for s in SERVICES:
        print(f"  {s['name']} → /hizmetler/{s['slug']}.html")
